In [1]:
print "Hallo"

Hallo


In [82]:
stringVariable = 'Hello'

In [83]:
type(stringVariable)

str

In [22]:
intVariable = 3

In [23]:
type(intVariable)

int

In [24]:
floatVariable = 3.

In [25]:
type(floatVariable)

float

In [29]:
boolVar = True

In [30]:
type(boolVar)

bool

In [57]:
if not ((type(floatVariable) == float)):
    print ("yes")

In [52]:
if 2:
    print (0)
else:
    print (1)

0


In [58]:
import numpy as np

In [59]:
a = 3 

In [60]:
type(a)

int

In [81]:
np.int16(3).dtype 

dtype('int16')

-2147483618

In [90]:
stringVariable

'Hello'

In [121]:
myList = ['Hello', 1, 2., 3., 5, 6]

In [123]:
print(myList[4])

5


In [136]:
myArray = np.array([[1. ,2. ],[3. , 4. ]])

In [144]:
#print (myArray[0])
#print (myArray[1])
print (myArray[0] + myArray[1])

[ 4.  6.]


In [145]:
myList[1:]

[1, 2.0, 3.0, 5, 6]

In [130]:
myOtherArray = np.array(myList[1:])

In [132]:
2 * myOtherArray

array([  2.,   4.,   6.,  10.,  12.])

In [134]:
myList[1:] + ["Hello", "there"]

[1, 2.0, 3.0, 5, 6, 'Hello', 'there']

In [152]:
myArray

array([[ 1.,  2.],
       [ 3.,  4.]])

In [150]:
myArray.reshape((4,1))

array([[ 1.],
       [ 2.],
       [ 3.],
       [ 4.]])

In [154]:
myThirdArray = np.array([1, 2, 3, 4, 5])

In [156]:
(myThirdArray > 2)

array([False, False,  True,  True,  True], dtype=bool)

In [176]:
myThirdArray[4:1:-1]

array([5, 4, 3])

In [172]:
 5 % 2

1.5

### create anumpy array containing numbers from 1 to 10
### extract only even numbers with boolean operations
# reverse it 
# make all those number odd

In [179]:
thisArray = np.array(range(1,11))

In [206]:
list(thisArray)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [207]:
(list(thisArray)[(thisArray % 2) == 0])[1:5] 

TypeError: only integer arrays with one element can be converted to an index

In [203]:
(thisArray % 2) == 0

array([False,  True, False,  True, False,  True, False,  True, False,  True], dtype=bool)

def extractValues(dataarr):
    if type(dataarr) == np.ndarray:
        return dataarr[-1::-1]
    return -1
    #print "Hi"
    #return 0

In [231]:
extractValues(np.arange(0,10,2))

array([8, 6, 4, 2, 0])

In [232]:
extractValues(3)

-1

# create a function that takes a string
# checks if the string is a palindrome
# returns 1 if true
# return -1 if false
# and also prints "Yes its a palindrome"
# or "this is not a palindrome"
# if you finish early add a print statement that prints 
#  ONLY the unique part (rad in radar)


In [255]:
def lookForPal(string):
    if string.lower() == string.lower()[::-1]: 
        #if len(string) % 2 :
        #    halfpal = string[:int(len(string) / 2 + 1)]
        #else: 
        #    halfpal = string[:int(len(string) / 2)]            
        halfpal = string[:int((float(len(string)) / 2.0) + 0.5)]
        print ("Yes its a palindrome", halfpal)
        return (1)
    print ("this is not a palindrome")
    return (-1)

In [256]:
lookForPal('Hannah')

('Yes its a palindrome', 'Han')


1

In [275]:
' '.join('The fox eats the rabbit '.strip().split(' ')).replace('rabbit', 'mouse')

'The fox eats the mouse'

In [282]:
fout = open("temp.txt", "w")

In [283]:
for i in range(10):
    for j in range(10):
        print >> fout, j, " ",
    print >> fout,  ""

In [284]:
fout.close()

In [292]:
tmpList = []

fin = open("temp.txt", "r")
for ln in fin.readlines():
    for dig in ln.split():
        tmpList.append(int(dig))

In [293]:
tmpList

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9]